collections:
  getting-started:
      output: true
  developer-guide:
     output: true
  integrator-guide:
     output: true
  references:
     output: true

algolia:
  application_id: 'V2486N1OKP'
  index_name:     'test_elasticio'